{% set name = "chromadb" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chromadb-{{ version }}.tar.gz
  sha256: c8f34c0b704b9108b04491480a36d42e894a960429f87c6516027b5481d59ed3

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
    - setuptools-scm
    - pip
  run:
    - typing_extensions
    - uvicorn 
    - rich 
    - httpx
    - orjson
    - python-build
    - mmh3 
    - opentelemetry-instrumentation
    - opentelemetry-instrumentation-fastapi 
    - pyyaml 
    - opentelemetry-api
    - opentelemetry-exporter-otlp-proto-grpc
    #- opentelemetry-sdk 
    - python-kubernetes
    - tenacity 
    - grpcio
    - typer
    - bcrypt
    - python
    - fastapi
    - chroma-hnswlib
    - importlib-resources
    - numpy 
    - onnxruntime
    - overrides 
    - posthog 
    - pulsar-client
    - pydantic
    - pypika 
    - requests
    - tokenizers
    - tqdm 
    - typing-extensions
    - uvicorn-standard

test:
  imports:
    - chromadb
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://www.trychroma.com/
  summary: "Chroma: The AI-native open-source embedding database"
  license: Apache-2.0
  license_file:
    - LICENSE
    - clients/js/LICENSE
  description: |
    Chroma is the open-source embedding database. Chroma makes it easy to build
    LLM apps by making knowledge, facts, and skills pluggable for LLMs.

    ![banner](https://docs.trychroma.com/img/hrm4.svg)

    PyPI: [https://pypi.org/project/chromadb](https://pypi.org/project/chromadb)

    ---

    :fire: The conda-forge recipe was generated with [Conda-Forger App](https://sugatoray-conda-forger.streamlit.app/).

    :point_right: [![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://sugatoray-conda-forger.streamlit.app/)

    [_streamlit-conda-forger-app]: https://sugatoray-conda-forger.streamlit.app/

  dev_url: https://github.com/chroma-core/chroma
  doc_url: https://docs.trychroma.com/

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/70829
    reason: Client request
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - sugatoray
    - xhochy
    - pavelzw
