{% set name = "chromadb" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chromadb-{{ version }}.tar.gz
    sha256: 96498ed141e71f1fce2e40f1bdce89020182f9fceed8d8e30d3a40e07be3d488
  - url: https://raw.githubusercontent.com/chroma-core/chroma/refs/tags/{{ version }}/LICENSE
    sha256: c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4
    fn: LICENSE

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    #- {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    # Needed for protoc
    - libprotobuf
    - make
    - python                                 # [build_platform != target_platform]
    #- cross-python_{{ target_platform }}     # [build_platform != target_platform]
    #- maturin >=1.0,<2.0                     # [build_platform != target_platform]
  host:
    - python
    - maturin
    - setuptools
    - setuptools-scm
    - pip
  run:
    - jsonschema
    - typing_extensions
    - uvicorn
    - rich 
    - httpx
    - orjson
    - python-build
    - mmh3 
    #- opentelemetry-instrumentation-fastapi ==0.41b0
    - opentelemetry-instrumentation-fastapi 
    - pyyaml
    - opentelemetry-api
    - opentelemetry-exporter-otlp-proto-grpc
    - opentelemetry-sdk
    - python-kubernetes
    - tenacity
    - grpcio 
    - typer 
    - bcrypt
    - python
    - fastapi
    - importlib-resources
    - numpy 
    - onnxruntime
    - overrides 
    - posthog 
    - pulsar-client 
    - pydantic 
    - pypika 
    - requests
    - tokenizers
    - tqdm 
    - typing-extensions
    - uvicorn-standard

test:
  imports:
    - chromadb
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://www.trychroma.com/
  summary: "Chroma: The AI-native open-source embedding database"
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: |
    Chroma is the open-source embedding database. Chroma makes it easy to build
    LLM apps by making knowledge, facts, and skills pluggable for LLMs.
  dev_url: https://github.com/chroma-core/chroma
  doc_url: https://docs.trychroma.com/

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/70829
    reason: Dependency for chromadb
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - sugatoray
    - xhochy
    - pavelzw
